# To use this config,
# 1. clone tmp 
#    $ git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# 2. copy this config file to `~/.tmux.conf`
# 3. open tmux
#    $ tmux kill-server
#    $ tmux
# 4. Inside tmux, run `Ctrl`+`A`, followed by `I` (capital i), to install the plugins

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

set-window-option -g mode-keys vi 
bind-key -T copy-mode-vi v send-key -X begin-selection
bind-key -T copy-mode-vi y send-key -X copy-selection-and-cancel

# install the tmux plugin mamager first, see https://github.com/tmux-plugins/tpm
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'wfxr/tmux-power'

### powerline: no time only date ###
set -g @tmux_power_right_arrow_icon ''
set -g @tmux_power_left_arrow_icon  ''
set -g @tmux_power_left_a  ''
set -g @tmux_power_left_b  ' #S'   
set -g @tmux_power_left_c  ''
set -g @tmux_power_left_d  ''
set -g @tmux_power_right_w ''
set -g @tmux_power_right_x ''
set -g @tmux_power_right_y ' %F'
set -g @tmux_power_right_z  ' #{USER}@#h'  # user@host
####################################

# ### powerline: normal ###
# set -g @tmux_power_right_arrow_icon ''
# set -g @tmux_power_left_arrow_icon  ''
# set -g @tmux_power_left_a  ''
# set -g @tmux_power_left_b  ' #S'   
# set -g @tmux_power_left_c  ''
# set -g @tmux_power_left_d  ''
# set -g @tmux_power_right_w ''
# set -g @tmux_power_right_x ' #{USER}@#h'
# set -g @tmux_power_right_y ' %F'
# set -g @tmux_power_right_z ' %T'
# #########################


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
